- hosts: work1
  gather_facts: yes

  vars:
    - bsc_node_path: /mnt/vol
  roles:
    - node
  vars_prompt:
    name: node_version
    prompt: 'Choose your Node version'
    default: '14.16.0'
    private: no

  tasks:
    - name: Install unzip
      become: true
      apt:
        name: unzip
        state: latest

    - name: nodejs info
      command: node -v
      command: npm -v
      register: out

    - debug: var=out.stdout_lines

    - name: install pm2
      become: true
      npm:
        name: pm2
        global: yes

    - name: check pm2 version
      command: pm2 -V
      register: pm
      environment:
        PATH: "/root/.npm-global/bin:{{ ansible_env.PATH }}"

    - debug: var=pm.stdout_lines

    - name: mkdir bsc folders
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - "{{bsc_node_path}}/bsc"
        - "{{bsc_node_path}}/bsc/mainnet-datadir"

    - name: download bsc v1.0.7
      get_url:
        url: https://github.com/binance-chain/bsc/releases/download/v1.0.7/geth_linux
        dest: /tmp/

    - name: set bsc to PATH
      become: true
      copy:
        remote_src: true # 远程服务器文件
        src: /tmp/geth_linux
        dest: /usr/local/bin/bsc
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u+x

    - name: show bsc version
      shell: bsc version
      register: bsc_version

    - debug: var=bsc_version.stdout_lines

    - name: download bsc config v1.0.7
      get_url:
        url: https://github.com/binance-chain/bsc/releases/download/v1.0.7/mainnet.zip
        dest: /tmp/

    - name: create bsc config folder
      command: "mkdir -p {{bsc_node_path}}/bsc/mainnet/"

    - name: unarchive bsc config folder
      unarchive:
        src: /tmp/mainnet.zip
        dest: "{{bsc_node_path}}/bsc/mainnet/"
        remote_src: yes

    - name: modify bsc config (添加注释 HTTPHost)
      lineinfile:
        path: "{{bsc_node_path}}/bsc/mainnet/config.toml"
        regex: '^(HTTPHost)(.*)'
        line: '# \1\2'
        backrefs: yes
        state: present

    - name: modify bsc config (添加注释 HTTPVirtualHosts)
      lineinfile:
        path: "{{bsc_node_path}}/bsc/mainnet/config.toml"
        regex: '^(HTTPVirtualHosts)(.*)'
        line: '# \1\2'
        backrefs: yes
        state: present

    - name: init bsc node
      shell: "bsc --datadir {{bsc_node_path}}/bsc/mainnet-datadir init {{bsc_node_path}}/bsc/mainnet/genesis.json"

    - name: create run-mainnet-fast.sh file
      copy:
        content: "/usr/local/bin/bsc --config {{bsc_node_path}}/bsc/mainnet/config.toml --datadir {{bsc_node_path}}/bsc/mainnet-datadir --syncmode fast --rpc --rpcaddr=0.0.0.0 --rpcport 18545 --rpccorsdomain '*' --ws --wsaddr=0.0.0.0 --wsport 18546 --wsorigins=*"
        dest: "{{bsc_node_path}}/bsc/run-mainnet-fast.sh"
        mode: u+x

    - name: launch bsc node
      shell: "pm2 start {{bsc_node_path}}/bsc/run-mainnet-fast.sh --name bsc-mainnet-fast --interpreter bash"
      environment:
        PATH: "/root/.npm-global/bin:{{ ansible_env.PATH }}"
